### ISSUE TITLE
코틀린의 기본예외는 어떤것들이 있고 자바와 어떤차이가 있나요?

### ISSUE THREAD

**Issue by beng9re** [Doolki/kotlin-in-action#11]
궁금합니다.

**Comment by babysean** [comment]
### 자바와 코틀린의 예외처리의 차이점
1. 예외 인스턴스를 만들 때 `new`를 붙일 필요가 없습니다.
2. 코틀린의 `throw`는 식이므로 다른 식에 포함될 수 있습니다.
3. 함수가 던질 수 있는 예외를 명시할 필요가 없습니다.
4. 예외 타입을 `:` 오른쪽에 씁니다.

**Comment by babysean** [comment]
### CheckedException - 컴파일시 발생하는 Exception (코틀린 미지원)
- IOException
- FileNotFoundException
- SocketException
- SQLException

### UnCheckedException - 런타임시 발생하는 Exception
- RuntimeException을 상속 받는 모든 예외

**Comment by beng9re** [comment]
+ 코틀린에서는 자바의 기본 체크드익셉션을 런타임익셉션으로 바라본다고 해요
