### ISSUE TITLE
이터레이션은 무엇일까요?

### ISSUE THREAD

**Issue by beng9re** [Doolki/kotlin-in-action#13]

**Comment by babysean** [comment]
### 이터레이션이란

 컬렉션 요소를 순차적으로 접근하는 방식을 말합니다. 즉, ***반복문*** 입니다.

 코틀린의 이터레이션은 `while`, `for`이 있습니다.
`while`은 자바와 동일하기에 자바의 `while`을 잘 안다면 따로 학습하지 않아도 됩니다.
코틀린에서는 초기값, 증가값, 최종값을 사용하는 자바의 `for` 형태의 요소가 없고, 자바의 `for-each` 형태의 루프 요소만 존재합니다. 

```kotlin
fun main(args: Array<String>) {
  for (i in 1..100) {
    println("숫자: ${i}")
  }
}
```

코틀린은 `for`를 대신하기 위해 범위<sup>range</sup>를 사용합니다.
`..` 연산자로 시작값과 끝값을 연결해서 범위를 만들어 사용합니다.

**Comment by beng9re** [comment]
좋습니다 !
