### ISSUE TITLE
확장 함수를 오버라이드할 수 없는 이유

### ISSUE THREAD

**Issue by babysean** [Doolki/kotlin-in-action#18]

**Comment by nowonsang** [comment]
확장 함수를 오버라이드 할 수 없는 이유는

확장함수 개념자체가

클래스 메서드 안에 명시되어있는것이 아닌 클래스 밖에 선언이 되기 때문에 

오버라이딩 할 수 가 없습니다.

간단한 예)

open class View {
    open fun click() = println("View clicked")
    open fun View.showOff() =  println("I'm a View!"); 
}
class Button: View() {//View 클래스를 상속받는 Button 클래스
    override fun click() = println("Button clicked")
    override fun View.showOff() =  println("I'm a button!");
}
//클래스 안에 확장함수를 넣어서 오버라이딩 해도 이것을 불러올수가 없다. -> 확장함수는 클래스 밖에 명시되어 사용해야하기 때문

fun View.showOff() = println("I'm a View!")
fun Button.showOff() = println("I'm a button!");

    /* 확장 함수는 클래스의 일부가 아니고 확장함수는 클래스 밖에서 선언된 형태만 불러올수있다.*/
    val function: View = Button() //자식 클래스를 생성해서 
    function.showOff(); // I'm a View! //showOff()를 불러와도 확장타입은 View를 바라보고 있기 때문에

I`m a View 라는 출력객체가 호출이 되는것을 볼수있습니다.
