### ISSUE TITLE
코틀린의 문법상 확장 함수는 반드시 짧은 이름을 써야 하는 이유

### ISSUE THREAD

**Issue by KIMYUNHA9701** [Doolki/kotlin-in-action#19]

**Comment by nowonsang** [comment]
코틀린에서 확장 함수가 반드시 짧은 이름을 사용해야 한다는 규칙은 없는것 같습니다.

확장 함수의 이름에 대한 제한은 일반 함수의 이름에 대한 제한과 동일하다고 봅니다.

즉, 의미 있는, 읽기 쉬운, 그리고 목적을 잘 나타내는 이름을 사용 하는것을 권장하는데

그이유는 이름이 길고 복잡하면 코드의 가독성을 해칠 수 있기때문이지 않을까 생각합니다.

**Comment by beng9re** [comment]
딱히 코틀린에서 막지는 않아서 찾아보니 코딩규칙정도로 이해하시면 될꺼 같아요
