### ISSUE TITLE
중첩 클래스가 이해가 되지 않습니다

### ISSUE THREAD

**Issue by babysean** [Doolki/kotlin-in-action#24]

**Comment by Lee-YuGyeong** [comment]
중첩 클래스는 형태만 내부에 존재할 뿐 실질적으로는 내용을 서로 공유할 수 없는 별개의 클래스입니다.

자바에서는 A 킅래스 안에 B 클래스를 정의하면 B 클래스는 자동으로 내부 클래스가 되지만 코틀린에서는 중첩클래스가 됩니다.

다른 클래스와 협력할 일이 적고 외부 클래스와 밀접한 관련이 있어 두 클래스를 한번에 관리하는 것이 적합하다고 판별되면 중첩 클래스를 사용하여 불필요한 관계를 감추고 높은 접근성을 얻을 수 있습니다.

이러한 중첩 클래스를 사용하면 소스의 가독성과 유지보수성을 높일 수 있습니다.

**Comment by beng9re** [comment]
![image](https://github.com/Doolki/kotlin-in-action/assets/26699273/fef68f65-f489-46f2-af6e-79420f3aa935)
