### ISSUE TITLE
가시성 변경자 internal 의 범위

### ISSUE THREAD

**Issue by babysean** [Doolki/kotlin-in-action#25]
가시성 변경자 internal은 같은 모듈에서만 볼 수 있다고 되어있다.
여기서 모듈은 어떤 범위를 의미인가 ?

**Comment by Lee-YuGyeong** [comment]
프로젝트 안에 모듈이 있고 모듈은 패키지로 구성되어 있습니다.

보통 대규모 프로젝트를 진행할 때 기능을 모듈로 분리하여 관리합니다. 

<img width="682" alt="image" src="https://github.com/Doolki/kotlin-in-action/assets/60072190/55ae3f14-974f-4989-8be0-6674001c876a">
