### ISSUE TITLE
인터페이스에는 아무런 상태도 들어갈 수 없다는 뜻은 무엇인가요 ?

### ISSUE THREAD

**Issue by babysean** [Doolki/kotlin-in-action#27]
프로퍼티를 선언할 수는 있지만 초기화할 수는 없습니다.

프로퍼티를 **초기화**하는 행위가 ***상태를 지정 또는 변경***한다는 의미 일까요 ?

**Comment by Lee-YuGyeong** [comment]
"인터페이스에는 아무런 상태도 들어갈 수 없다"라는 뜻은 실제로 값을 가지는 상태가 될 수 없다는 것을 의미합니다.

상태를 저장하는 역할은 주로 클래스가 담당하며, 인터페이스는 행동(메소드)의 규약을 정의하는 데 사용됩니다.

프로퍼티를 초기화하는 행위는 프로퍼티에 값을 할당하거나 설정하는 과정으로, 상태를 지정한다고 생각하면 될 것 같습니다.

<img width="364" alt="image" src="https://github.com/Doolki/kotlin-in-action/assets/60072190/8dc8ab05-0b8e-405f-b51e-58678047e6b7">

인터페이스에 프로퍼티를 선언하여 초기화를 시키면 인터페이스 안에서는 프로퍼티를 초기화 할 수 없다는 에러가 뜨는 것을 볼 수 있습니다.

<img width="248" alt="image" src="https://github.com/Doolki/kotlin-in-action/assets/60072190/e7072f49-5144-48d2-b77b-77f3d3c55fae">

해당 오류를 고치기 위해서는 인터페이스에서는 프로퍼티를 선언만 해주고 초기화는 해당 인터페이스를 구현한 클래스에서  해주시면 됩니다.
