### ISSUE TITLE
함수형 프로그래밍 vs 객체지향 프로그래밍

### ISSUE THREAD

**Issue by babysean** [Doolki/kotlin-in-action#8]
함수형 프로그래밍의 핵심 개념을 학습합니다

1. first-class 함수
2. immutability
3. side effect 없음 - 순수함수(pure function)

**Comment by beng9re** [comment]
1. 특정 프로그래밍 언어에서 함수가 변수처럼 다뤄지는 경우, 이를 first class function, 일급 함수라고 합니다.
2. 불변성 항상 함수의 (입력과 출력이 같은것)
3. 외부의 요소의 영향을 받지 않는것 

-- 관련 코드 작성하고 클로징 하시죠

**Comment by babysean** [comment]
LGTM 👍🏼
